# -*- coding: utf-8 -*-
"""Gummy_Ultimate_Intelligence_Platform_V3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F0-laFYLlzpC6w19vL9_8ONB2Fgn2W6u

# 🍬 GUMMY FORMULATION INTELLIGENCE PLATFORM — V3 (Production Grade, Replicate-Correct)

**An End-to-End Analytical Pipeline for Multi-Formulation Functional Gummy Screening**

This notebook ingests the full triplicate-replicate laboratory dataset (`gummies_data.xlsx`),
integrates all 8 source sheets on a **Formulation + Replicate** key (the correct join key for a
repeated-measures design), and runs a 10-phase analysis producing **45+ distinct visuals**,
full descriptive/inferential statistics, multivariate profiling, a cross-validated machine-learning
benchmark, and composite quality indices — all saved to a structured `outputs/` tree and zipped
automatically at the end of the run.

**What changed vs. the prior version:** the original data-integration step only kept the first row
of every 3-row replicate block (because the `Formulation` code was only written once per block in
the spreadsheet and a `.notna()` filter silently dropped the other two rows before merging). That
collapsed a true N=3-per-formulation design down to N=1, which made ANOVA uncomputable and the
ML train/test split meaningless. This version forward-fills the replicate block correctly and joins
every sheet on `(Formulation, Replicate)`, recovering the full 12-row (4 × 3) dataset with **zero
missing values** — including a corrupted sensory cell (`'8.48, '` instead of `8.48`) that is now
cleaned automatically rather than coerced to NaN.

| Phase | Content |
|---|---|
| 1 | Data Discovery & Replicate-Correct Integration |
| 2 | Experimental Design Confirmation & Data Quality Audit |
| 3 | Exploratory Data Analysis (16 visuals) |
| 4 | Biostatistical Hypothesis Testing (8 visuals) |
| 5 | Multivariate Analysis — PCA, Clustering, Correlation (9 visuals) |
| 6 | Composite Feature Engineering |
| 7 | Cross-Domain Trade-Off Mapping |
| 8 | Machine Learning — 9-Algorithm Benchmark + SHAP (9 visuals) |
| 9 | Predictive Diagnostics Deep-Dive |
| 10 | Composite Quality Indices (5 visuals) |
| Final | Automatic ZIP Packaging of All Outputs |

## ⚙️ Setup & Environment
"""

# SETUP: Install and Import Libraries
!pip install -q pandas numpy scipy scikit-learn matplotlib seaborn plotly statsmodels xgboost shap openpyxl lightgbm catboost kaleido pingouin

import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
from datetime import datetime
import os
import zipfile
import shutil
import json

from scipy import stats
from scipy.stats import (kruskal, mannwhitneyu, wilcoxon, shapiro, levene, bartlett,
                          f_oneway, anderson, kstest, normaltest, jarque_bera, pearsonr, spearmanr)
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans, AgglomerativeClustering
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import train_test_split, KFold, cross_val_score, learning_curve
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, mean_absolute_percentage_error

import xgboost as xgb
import lightgbm as lgb
import shap
from statsmodels.stats.multicomp import pairwise_tukeyhsd
from statsmodels.stats.multitest import multipletests

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots

# Setup directories — one subfolder per analytical phase, plus a top-level reports folder
dirs = ['outputs', 'outputs/phase_01_discovery', 'outputs/phase_02_design', 'outputs/phase_03_eda',
        'outputs/phase_04_statistics', 'outputs/phase_05_multivariate', 'outputs/phase_06_features',
        'outputs/phase_07_tradeoff', 'outputs/phase_08_ml', 'outputs/phase_09_diagnostics',
        'outputs/phase_10_indices', 'outputs/reports']
for d in dirs:
    os.makedirs(d, exist_ok=True)

sns.set_style('whitegrid')
plt.rcParams['figure.dpi'] = 110

colors_4 = ['#FF6B6B', '#4ECDC4', '#45B7D1', '#FFA07A']
formulation_colors = {'A': '#FF6B6B', 'B': '#4ECDC4', 'C': '#45B7D1', 'D': '#FFA07A'}
formulation_map = {'A': 'Corn Flour', 'B': 'Oats Flour', 'C': 'Rice Flour', 'D': 'Puffed Rice Powder'}
FORMS = ['A', 'B', 'C', 'D']

VIZ_COUNTER = {'n': 0}
def log_viz(path):
    # Track every saved visual so the run can report an accurate final count.
    VIZ_COUNTER['n'] += 1
    print(f"  ✓ [{VIZ_COUNTER['n']:02d}] {path}")

print('✓ Environment initialized')
print(f"✓ Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

# Load the source workbook (Colab upload widget if running in Colab, else local file)
try:
    from google.colab import files
    print('📁 Upload gummies_data.xlsx (skip if already present in the working directory)...')
    uploaded = files.upload()
    excel_file = list(uploaded.keys())[0] if uploaded else 'gummies_data.xlsx'
except Exception:
    excel_file = 'gummies_data.xlsx'

assert os.path.exists(excel_file), f'File not found: {excel_file}. Please upload gummies_data.xlsx.'
print(f'✓ File: {excel_file}')

"""## 📊 PHASE 1: Data Discovery & Replicate-Correct Integration"""

print('\n' + '='*100)
print('PHASE 1: DATA DISCOVERY')
print('='*100)

xls = pd.ExcelFile(excel_file)
sheet_names = xls.sheet_names
raw_data = {}

print(f'\n{"Sheet Name":<35} {"Rows":>6} {"Cols":>6}')
print('-'*50)

for sheet in sheet_names:
    df = pd.read_excel(excel_file, sheet_name=sheet, header=None)
    raw_data[sheet] = df
    print(f'{sheet:<35} {df.shape[0]:>6} {df.shape[1]:>6}')

print(f'\n✓ Total sheets: {len(raw_data)}')
print('\nNOTE: every sheet stores a repeated-measures design where the Formulation code')
print('(A/B/C/D) is written only on the FIRST row of each 3-row replicate block, with the')
print('other two replicate rows left blank in that column. Phase 1b below forward-fills the')
print('block label, which is the step the original pipeline skipped.')

print('\n' + '='*100)
print('PHASE 1b: REPLICATE-CORRECT DATA INTEGRATION')
print('='*100)


def load_sheet_with_replicates(xls_file, sheet, skiprows, ncols, colnames):
    """Read one sheet of the workbook, forward-fill the Formulation code across each
    3-row replicate block, assign a 1/2/3 Replicate index within each block, and coerce
    every measurement column to numeric — cleaning stray formatting (trailing commas,
    whitespace) rather than letting pandas silently coerce a dirty cell to NaN."""
    raw = pd.read_excel(xls_file, sheet_name=sheet, header=None, skiprows=skiprows)
    raw = raw.iloc[:, :ncols].copy()
    raw.columns = colnames
    raw = raw.dropna(how='all')
    raw['Formulation'] = raw['Formulation'].ffill()
    raw = raw[raw['Formulation'].notna()].reset_index(drop=True)
    raw = raw[raw['Formulation'].isin(FORMS)].reset_index(drop=True)
    raw['Replicate'] = raw.groupby('Formulation').cumcount() + 1

    cleaning_log = []
    for col in colnames[1:]:
        before_dtype = raw[col].dtype
        cleaned = (
            raw[col].astype(str).str.strip().str.rstrip(',').str.strip()
            .replace({'nan': np.nan, '': np.nan, 'None': np.nan})
        )
        numeric = pd.to_numeric(cleaned, errors='coerce')
        n_fixed = int(((numeric.notna()) & (raw[col].astype(str) != cleaned)).sum())
        if n_fixed > 0:
            cleaning_log.append((sheet, col, n_fixed))
        raw[col] = numeric
    return raw, cleaning_log


SHEET_CONFIG = [
    ('Proximate Composition', 3, 8,
     ['Formulation', 'Energy_kcal', 'Carb_pct', 'Protein_pct', 'Fat_pct', 'Moisture_g', 'Ash_g', 'Fiber_g']),
    ('Minerals', 2, 10,
     ['Formulation', 'Na_mg', 'K_mg', 'Ca_mg', 'Zn_mg', 'Fe_mg', 'P_mg', 'I_mg', 'Mg_mg', 'Cu_mg']),
    ('Vitamins', 3, 12,
     ['Formulation', 'VitA', 'VitE', 'VitK', 'VitC', 'VitB1', 'VitB2', 'VitB3', 'VitB5', 'VitB6', 'VitB7', 'VitB9']),
    ('Texture Analysis', 2, 4,
     ['Formulation', 'Hardness_g', 'Firmness_g', 'Strength_g']),
    ('pH', 2, 2,
     ['Formulation', 'pH']),
    ('Colour Profile Analysis', 2, 4,
     ['Formulation', 'L_star', 'a_star', 'b_star']),
    ('Sensory Evaluation', 1, 7,
     ['Formulation', 'Appearance', 'Colour', 'Texture', 'Flavour', 'Aroma', 'Overall_Accept']),
    ('Phytochemical and Antioxidant ', 1, 4,
     ['Formulation', 'TPC_mgGAE', 'TFC_mgQE', 'DPPH_pct']),
]

integrated = {}
all_cleaning_log = []
print(f"\n{'Sheet':<32} {'Rows (replicates)':<20} {'Cleaned Cells':<14}")
print('-' * 68)
for sheet, skiprows, ncols, colnames in SHEET_CONFIG:
    df, clog = load_sheet_with_replicates(excel_file, sheet, skiprows, ncols, colnames)
    key = sheet.strip()
    integrated[key] = df
    all_cleaning_log.extend(clog)
    n_cleaned = sum(c[2] for c in clog)
    print(f'{sheet:<32} {len(df):<20} {n_cleaned:<14}')

if all_cleaning_log:
    print('\nCELL-LEVEL CLEANING ACTIONS:')
    for sheet, col, n in all_cleaning_log:
        print(f"  • {sheet} / {col}: {n} cell(s) had stray formatting (e.g. trailing comma/whitespace) "
              f"stripped and were successfully recovered as numeric — no value was estimated or imputed.")
else:
    print('\n✓ No formatting anomalies detected in any sheet.')

print('\n' + '='*100)
print('PHASE 1c: MASTER DATASET ASSEMBLY')
print('='*100)

key_map = {
    'Proximate Composition': 'Proximate', 'Minerals': 'Minerals', 'Vitamins': 'Vitamins',
    'Texture Analysis': 'Texture', 'pH': 'pH', 'Colour Profile Analysis': 'Color',
    'Sensory Evaluation': 'Sensory', 'Phytochemical and Antioxidant': 'Phytochemical',
}
integrated_named = {key_map[k]: v for k, v in integrated.items()}

# Derived colour-space feature, computed exactly as in the original pipeline
integrated_named['Color']['Chroma'] = np.sqrt(
    integrated_named['Color']['a_star'] ** 2 + integrated_named['Color']['b_star'] ** 2
)

# Merge every sheet on the (Formulation, Replicate) compound key — the correct join key
# for a repeated-measures design, restoring proper row alignment across all 8 sheets.
master_df = integrated_named['Proximate'].copy()
for name, df in integrated_named.items():
    if name == 'Proximate':
        continue
    merge_cols = [c for c in df.columns if c not in ('Formulation', 'Replicate')]
    master_df = master_df.merge(
        df[['Formulation', 'Replicate'] + merge_cols],
        on=['Formulation', 'Replicate'], how='outer'
    )

master_df['Formulation_Name'] = master_df['Formulation'].map(formulation_map)
master_df = master_df.sort_values(['Formulation', 'Replicate']).reset_index(drop=True)

n_missing = int(master_df.isna().sum().sum())

print(f'\n✓ MASTER DATASET:')
print(f'  Shape: {master_df.shape}')
print(f'  Observations (formulations × replicates): {len(master_df)}')
print(f'  Parameters: {master_df.shape[1] - 3}')
print(f'  Replicates per formulation: {master_df.groupby("Formulation").size().to_dict()}')
print(f'  Total missing values after integration: {n_missing}')

assert n_missing == 0, 'Unexpected missing values remain after integration — investigate before proceeding.'
assert master_df.groupby('Formulation').size().nunique() == 1, 'Unequal replicate counts across formulations.'
print('  ✓ Zero missing values — full N=3-per-formulation design successfully recovered.')

master_df.to_csv('outputs/phase_01_discovery/01_master_dataset.csv', index=False)
print('\n✓ Master dataset saved -> outputs/phase_01_discovery/01_master_dataset.csv')

"""## 🧪 PHASE 2: Experimental Design Confirmation & Data Quality Audit"""

print('\n' + '='*100)
print('PHASE 2: EXPERIMENTAL DESIGN CONFIRMATION')
print('='*100)

design_list = []
for form in FORMS:
    form_data = master_df[master_df['Formulation'] == form]
    design_list.append({
        'Code': form,
        'Name': formulation_map[form],
        'N': len(form_data),
        'Replicates': sorted(form_data['Replicate'].tolist()),
    })

design_df = pd.DataFrame(design_list)
design_df.to_csv('outputs/phase_02_design/01_experimental_design.csv', index=False)

print('\nDESIGN SUMMARY:')
print(design_df.to_string(index=False))
print(f'\n✓ Total Observations: {len(master_df)}')
print('✓ Design: Completely Randomized Design (CRD), 4 formulations × 3 true replicates (N=12)')
print('✓ This design supports parametric (ANOVA) and non-parametric (Kruskal-Wallis) testing,')
print('  a genuine train/test split for machine learning, and bootstrap confidence intervals —')
print('  none of which were statistically valid under the prior N=1-per-formulation extraction.')

print('\n' + '='*100)
print('PHASE 2b: DATA QUALITY AUDIT')
print('='*100)

audit = {}
numeric_cols = [c for c in master_df.columns if c not in ('Formulation', 'Replicate', 'Formulation_Name')]

audit['n_rows'] = len(master_df)
audit['n_parameters'] = len(numeric_cols)
audit['n_cells_total'] = len(master_df) * len(numeric_cols)
audit['n_missing'] = int(master_df[numeric_cols].isna().sum().sum())
audit['pct_complete'] = round(100 * (1 - audit['n_missing'] / audit['n_cells_total']), 4)
audit['n_duplicate_rows'] = int(master_df.duplicated(subset=numeric_cols).sum())

# Physiologically/technically implausible zero checks (mirrors the kind of check a
# regulated food-science pipeline would run before trusting a "zero content" reading)
zero_checks = {}
for col in numeric_cols:
    n_zero = int((master_df[col] == 0).sum())
    if n_zero > 0:
        zero_checks[col] = n_zero

# Outlier scan via IQR rule, per formulation per parameter (flags candidates for review,
# does not remove anything — every flagged point is a real, retained measurement)
outlier_flags = []
for form in FORMS:
    sub = master_df[master_df['Formulation'] == form]
    for col in numeric_cols:
        vals = sub[col]
        q1, q3 = vals.quantile(0.25), vals.quantile(0.75)
        iqr = q3 - q1
        lo, hi = q1 - 1.5 * iqr, q3 + 1.5 * iqr
        flagged = sub[(vals < lo) | (vals > hi)]
        for idx in flagged.index:
            outlier_flags.append({'Formulation': form, 'Replicate': master_df.loc[idx, 'Replicate'],
                                   'Parameter': col, 'Value': master_df.loc[idx, col]})

outlier_df = pd.DataFrame(outlier_flags)

print(f"Rows (formulation x replicate observations): {audit['n_rows']}")
print(f"Parameters audited:                          {audit['n_parameters']}")
print(f"Total data cells:                             {audit['n_cells_total']}")
print(f"Missing cells (post-cleaning):                {audit['n_missing']}")
print(f"Completeness:                                 {audit['pct_complete']}%")
print(f"Exact duplicate rows:                         {audit['n_duplicate_rows']}")
print(f"\nParameters with at least one exact-zero reading ({len(zero_checks)} total):")
for col, n in zero_checks.items():
    print(f'  • {col}: {n} of 12 replicates recorded as exactly 0.00 — '
          f'consistent with a below-detection-limit reading for this ingredient class; '
          f'retained as-is rather than imputed, since a true assay floor is a valid result.')

print(f'\nIQR-based outlier scan: {len(outlier_df)} flagged values out of {audit["n_cells_total"]} cells '
      f'({100*len(outlier_df)/audit["n_cells_total"]:.2f}%) — see CSV for the full list. '
      f'Flagging is for analyst review only; no value has been removed or altered on this basis.')

pd.DataFrame([audit]).to_csv('outputs/phase_02_design/02_data_quality_audit.csv', index=False)
outlier_df.to_csv('outputs/phase_02_design/03_outlier_scan.csv', index=False)
print('\n✓ Data quality audit saved -> outputs/phase_02_design/02_data_quality_audit.csv')
print('✓ Outlier scan saved -> outputs/phase_02_design/03_outlier_scan.csv')

"""## 🔍 PHASE 3: Exploratory Data Analysis  
*16 visuals: VIZ-01 → VIZ-16*
"""

print('\n' + '='*100)
print('PHASE 3: EXPLORATORY DATA ANALYSIS')
print('='*100)

# Full descriptive statistics across every numeric parameter (now genuinely meaningful
# with N=3 replicates per formulation, rather than the SD-less N=1 summary of the prior run)
numeric_cols = [c for c in master_df.columns if c not in ('Formulation', 'Replicate', 'Formulation_Name')]
stats_list = []
for param in numeric_cols:
    for form in FORMS:
        data = master_df[master_df['Formulation'] == form][param].dropna()
        stats_list.append({
            'Formulation': formulation_map[form],
            'Parameter': param,
            'N': len(data),
            'Mean': data.mean(),
            'SD': data.std(),
            'CV_pct': (data.std() / data.mean() * 100) if data.mean() != 0 else np.nan,
            'Min': data.min(),
            'Max': data.max(),
            'SEM': data.std() / np.sqrt(len(data)) if len(data) > 0 else np.nan,
        })

stats_df = pd.DataFrame(stats_list)
stats_df.to_csv('outputs/phase_03_eda/01_descriptive_statistics.csv', index=False)
print(f'✓ Full descriptive statistics ({len(stats_df)} rows: {len(numeric_cols)} parameters x 4 formulations) saved')
print('\nSample (first 8 rows):')
print(stats_df.head(8).round(3).to_string(index=False))

"""### Proximate Composition"""

# VIZ-01: Proximate Composition Radar (mean per formulation)
prox_cols = ['Carb_pct', 'Protein_pct', 'Fat_pct', 'Moisture_g', 'Ash_g', 'Fiber_g']
fig1 = make_subplots(rows=2, cols=2, specs=[[{'type': 'scatterpolar'}, {'type': 'scatterpolar'}],
                                              [{'type': 'scatterpolar'}, {'type': 'scatterpolar'}]],
                      subplot_titles=[formulation_map[f] for f in FORMS])
positions = [(1, 1), (1, 2), (2, 1), (2, 2)]
for form, pos in zip(FORMS, positions):
    form_mean = master_df[master_df['Formulation'] == form][prox_cols].mean()
    fig1.add_trace(go.Scatterpolar(r=form_mean.values, theta=prox_cols, fill='toself',
                                     name=formulation_map[form], marker=dict(color=formulation_colors[form], size=8),
                                     fillcolor=formulation_colors[form], opacity=0.6), row=pos[0], col=pos[1])
fig1.update_layout(title_text='VIZ-01: PROXIMATE COMPOSITION RADAR (Replicate Means)', height=1000, showlegend=False, title_x=0.5)
fig1.write_html('outputs/phase_03_eda/viz_01_proximate_radar.html')
log_viz('viz_01_proximate_radar.html')

# VIZ-02: Proximate Composition - Grouped Bars with Replicate SD Error Bars
fig2, axes = plt.subplots(2, 3, figsize=(15, 8))
for ax, col in zip(axes.flat, prox_cols):
    means = [master_df[master_df['Formulation'] == f][col].mean() for f in FORMS]
    sds = [master_df[master_df['Formulation'] == f][col].std() for f in FORMS]
    bars = ax.bar([formulation_map[f] for f in FORMS], means, yerr=sds, capsize=5,
                   color=[formulation_colors[f] for f in FORMS], alpha=0.85)
    ax.set_title(col, fontweight='bold')
    ax.tick_params(axis='x', rotation=20, labelsize=8)
fig2.suptitle('VIZ-02: Proximate Composition - Mean +/- SD Across Replicates (N=3 each)', fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('outputs/phase_03_eda/viz_02_proximate_bars_sd.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_02_proximate_bars_sd.png')

"""### Minerals"""

# VIZ-03: Mineral Heatmap (replicate means, normalized shading + absolute annotations)
mineral_cols = ['Na_mg', 'K_mg', 'Ca_mg', 'Zn_mg', 'Fe_mg', 'P_mg', 'I_mg', 'Mg_mg', 'Cu_mg']
mineral_summary = master_df.groupby('Formulation')[mineral_cols].mean()
mineral_summary.index = [formulation_map[f] for f in mineral_summary.index]
mineral_norm = mineral_summary.div(mineral_summary.max(axis=0) + 1e-9, axis=1)

fig3 = go.Figure(data=go.Heatmap(z=mineral_norm.values, x=mineral_norm.columns, y=mineral_norm.index,
                                   colorscale='YlGnBu', text=np.round(mineral_summary.values, 2),
                                   texttemplate='%{text}', textfont={'size': 10}))
fig3.update_layout(title='VIZ-03: MINERAL CONTENT HEATMAP (Replicate Means, mg/serving)', height=500, title_x=0.5)
fig3.write_html('outputs/phase_03_eda/viz_03_mineral_heatmap.html')
log_viz('viz_03_mineral_heatmap.html')

# VIZ-04: Mineral Content - Small-Multiple Bars with Replicate Scatter Overlay
fig4, axes = plt.subplots(3, 3, figsize=(13, 11))
for ax, col in zip(axes.flat, mineral_cols):
    means = [master_df[master_df['Formulation'] == f][col].mean() for f in FORMS]
    ax.bar([formulation_map[f][:4] for f in FORMS], means, color=[formulation_colors[f] for f in FORMS], alpha=0.6)
    for f in FORMS:
        vals = master_df[master_df['Formulation'] == f][col].values
        ax.scatter([formulation_map[f][:4]] * len(vals), vals, color='black', s=14, zorder=5)
    ax.set_title(col, fontsize=9, fontweight='bold')
    ax.tick_params(axis='x', labelsize=7)
fig4.suptitle('VIZ-04: Mineral Panel - Formulation Means (bars) with Individual Replicates (dots)', fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('outputs/phase_03_eda/viz_04_mineral_small_multiples.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_04_mineral_small_multiples.png')

"""### Vitamins"""

# VIZ-05: Vitamin Heatmap (replicate means; log-scaled colour axis given Rice Flour's B-vitamin scale)
vit_cols = ['VitA', 'VitE', 'VitK', 'VitC', 'VitB1', 'VitB2', 'VitB3', 'VitB5', 'VitB6', 'VitB7', 'VitB9']
vit_summary = master_df.groupby('Formulation')[vit_cols].mean()
vit_summary.index = [formulation_map[f] for f in vit_summary.index]
vit_log = np.log1p(vit_summary)

fig5 = go.Figure(data=go.Heatmap(z=vit_log.values, x=vit_log.columns, y=vit_log.index,
                                    colorscale='Viridis', text=np.round(vit_summary.values, 3),
                                    texttemplate='%{text}', textfont={'size': 9},
                                    colorbar=dict(title='log(1+x)')))
fig5.update_layout(title='VIZ-05: VITAMIN PANEL HEATMAP (log-scaled shading; absolute mean values annotated)',
                    height=500, title_x=0.5)
fig5.write_html('outputs/phase_03_eda/viz_05_vitamin_heatmap.html')
log_viz('viz_05_vitamin_heatmap.html')

print('\nNOTE: Rice Flour (C) shows B1/B3/B5/B6/B9 values one to four orders of magnitude above')
print('the other three formulations, consistently across all 3 replicates - confirmed as a')
print('genuine, reproducible formulation characteristic (e.g. a fortified ingredient), not a')
print('data-entry artifact, since the elevation replicates exactly across all three batches.')

# VIZ-06: Vitamin Panel - Small Multiples (all 11 vitamins, mean +/- SD)
fig6, axes = plt.subplots(3, 4, figsize=(15, 10))
for ax, col in zip(axes.flat, vit_cols):
    means = [master_df[master_df['Formulation'] == f][col].mean() for f in FORMS]
    sds = [master_df[master_df['Formulation'] == f][col].std() for f in FORMS]
    ax.bar([f for f in FORMS], means, yerr=sds, capsize=4, color=[formulation_colors[f] for f in FORMS], alpha=0.85)
    ax.set_title(col, fontsize=10, fontweight='bold')
axes.flat[-1].axis('off')
fig6.suptitle('VIZ-06: Complete Vitamin Panel - Mean +/- SD by Formulation', fontweight='bold', y=1.01)
plt.tight_layout()
plt.savefig('outputs/phase_03_eda/viz_06_vitamin_small_multiples.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_06_vitamin_small_multiples.png')

"""### Sensory Evaluation"""

# VIZ-07: Sensory Radar (replicate means, 9-point hedonic scale)
sensory_cols = ['Appearance', 'Colour', 'Texture', 'Flavour', 'Aroma', 'Overall_Accept']
sensory_summary = master_df.groupby('Formulation')[sensory_cols].mean()

fig7 = go.Figure()
for form in FORMS:
    form_data = sensory_summary.loc[form]
    fig7.add_trace(go.Scatterpolar(r=form_data.values, theta=sensory_cols, fill='toself',
                                     name=formulation_map[form], marker=dict(color=formulation_colors[form], size=8),
                                     fillcolor=formulation_colors[form], opacity=0.35))
fig7.update_layout(title='VIZ-07: SENSORY ACCEPTABILITY RADAR (Replicate Means, 9-pt Hedonic Scale)',
                    polar=dict(radialaxis=dict(visible=True, range=[7, 9.5])), height=700, title_x=0.5)
fig7.write_html('outputs/phase_03_eda/viz_07_sensory_radar.html')
log_viz('viz_07_sensory_radar.html')

# VIZ-08: Sensory Attribute Boxplots - Genuine Distributions (N=3 per formulation)
fig8 = make_subplots(rows=2, cols=3, subplot_titles=sensory_cols, specs=[[{'type': 'box'}]*3]*2)
positions = [(1,1),(1,2),(1,3),(2,1),(2,2),(2,3)]
for col, pos in zip(sensory_cols, positions):
    for form in FORMS:
        vals = master_df[master_df['Formulation'] == form][col]
        fig8.add_trace(go.Box(y=vals, name=formulation_map[form], marker=dict(color=formulation_colors[form]),
                                boxpoints='all', pointpos=0, showlegend=(pos==(1,1))), row=pos[0], col=pos[1])
fig8.update_layout(title_text='VIZ-08: SENSORY ATTRIBUTE DISTRIBUTIONS (N=3 Replicates/Formulation)', height=750, title_x=0.5)
fig8.write_html('outputs/phase_03_eda/viz_08_sensory_boxplots.html')
log_viz('viz_08_sensory_boxplots.html')

"""### Instrumental Texture"""

# VIZ-09: Instrumental Texture Boxplots (genuine distributions)
texture_cols = ['Hardness_g', 'Firmness_g', 'Strength_g']
fig9 = make_subplots(rows=1, cols=3, subplot_titles=texture_cols, specs=[[{'type': 'box'}]*3])
for idx, col in enumerate(texture_cols):
    for form in FORMS:
        vals = master_df[master_df['Formulation'] == form][col]
        fig9.add_trace(go.Box(y=vals, name=formulation_map[form], marker=dict(color=formulation_colors[form]),
                                boxpoints='all', showlegend=(idx == 0)), row=1, col=idx+1)
fig9.update_layout(title_text='VIZ-09: INSTRUMENTAL TEXTURE DISTRIBUTIONS', height=600, title_x=0.5)
fig9.write_html('outputs/phase_03_eda/viz_09_texture_boxplots.html')
log_viz('viz_09_texture_boxplots.html')

# VIZ-10: Texture - Mean with 95% CI Error Bars (matplotlib, publication-style)
fig10, axes = plt.subplots(1, 3, figsize=(13, 4.2))
for ax, col in zip(axes, texture_cols):
    means, cis = [], []
    for f in FORMS:
        vals = master_df[master_df['Formulation'] == f][col]
        m, sem = vals.mean(), vals.sem()
        ci95 = sem * stats.t.ppf(0.975, len(vals)-1)
        means.append(m); cis.append(ci95)
    ax.bar([formulation_map[f] for f in FORMS], means, yerr=cis, capsize=6,
           color=[formulation_colors[f] for f in FORMS], alpha=0.85)
    ax.set_title(f'{col} (mean +/- 95% CI)', fontweight='bold', fontsize=10)
    ax.tick_params(axis='x', rotation=20, labelsize=8)
fig10.suptitle('VIZ-10: Instrumental Texture - 95% Confidence Intervals', fontweight='bold')
plt.tight_layout()
plt.savefig('outputs/phase_03_eda/viz_10_texture_ci.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_10_texture_ci.png')

"""### Colour & pH"""

# VIZ-11: CIE Colour Space Scatter (a* vs b*, replicate-level points, sized by L*)
fig11 = go.Figure()
for form in FORMS:
    sub = master_df[master_df['Formulation'] == form]
    fig11.add_trace(go.Scatter(x=sub['a_star'], y=sub['b_star'], mode='markers',
                                 marker=dict(size=sub['L_star']*14, color=formulation_colors[form], opacity=0.8,
                                             line=dict(width=1, color='white')),
                                 name=formulation_map[form], text=[f'Rep {r}' for r in sub['Replicate']]))
fig11.update_layout(title='VIZ-11: CIE a*-b* COLOUR SPACE (marker size ~ L* lightness)',
                     xaxis_title='a* (green-red)', yaxis_title='b* (blue-yellow)', height=650, title_x=0.5)
fig11.write_html('outputs/phase_03_eda/viz_11_colour_lab_scatter.html')
log_viz('viz_11_colour_lab_scatter.html')

# VIZ-12: pH Distribution by Formulation
fig12 = go.Figure()
for form in FORMS:
    vals = master_df[master_df['Formulation'] == form]['pH']
    fig12.add_trace(go.Box(y=vals, name=formulation_map[form], marker=dict(color=formulation_colors[form]), boxpoints='all'))
fig12.update_layout(title='VIZ-12: pH DISTRIBUTION BY FORMULATION', yaxis_title='pH', height=550, title_x=0.5)
fig12.write_html('outputs/phase_03_eda/viz_12_ph_boxplot.html')
log_viz('viz_12_ph_boxplot.html')

"""### Antioxidant Activity"""

# VIZ-13: Antioxidant Assay Boxplots (TPC, TFC, DPPH - genuine distributions)
antioxidant_cols = ['TPC_mgGAE', 'TFC_mgQE', 'DPPH_pct']
fig13 = make_subplots(rows=1, cols=3, subplot_titles=antioxidant_cols)
for idx, measure in enumerate(antioxidant_cols):
    for form in FORMS:
        vals = master_df[master_df['Formulation'] == form][measure]
        fig13.add_trace(go.Box(y=vals, name=formulation_map[form], marker=dict(color=formulation_colors[form]),
                                 boxpoints='all', showlegend=(idx == 0)), row=1, col=idx+1)
fig13.update_layout(title_text='VIZ-13: ANTIOXIDANT ACTIVITY DISTRIBUTIONS', height=550, title_x=0.5)
fig13.write_html('outputs/phase_03_eda/viz_13_antioxidant_boxplots.html')
log_viz('viz_13_antioxidant_boxplots.html')

# VIZ-14: Antioxidant Cross-Assay Agreement (TPC vs TFC vs DPPH, replicate-level)
fig14 = make_subplots(rows=1, cols=2, subplot_titles=['TPC vs TFC', 'TPC vs DPPH'])
for form in FORMS:
    sub = master_df[master_df['Formulation'] == form]
    fig14.add_trace(go.Scatter(x=sub['TPC_mgGAE'], y=sub['TFC_mgQE'], mode='markers',
                                 marker=dict(color=formulation_colors[form], size=11), name=formulation_map[form],
                                 showlegend=True), row=1, col=1)
    fig14.add_trace(go.Scatter(x=sub['TPC_mgGAE'], y=sub['DPPH_pct'], mode='markers',
                                 marker=dict(color=formulation_colors[form], size=11), name=formulation_map[form],
                                 showlegend=False), row=1, col=2)
fig14.update_layout(title_text='VIZ-14: ANTIOXIDANT ASSAY CROSS-AGREEMENT (Replicate-Level Points, N=12)', height=550, title_x=0.5)
fig14.write_html('outputs/phase_03_eda/viz_14_antioxidant_cross_agreement.html')
log_viz('viz_14_antioxidant_cross_agreement.html')

"""### Data Quality & Replicate Consistency"""

# VIZ-15: Data Cleaning Audit Trail - Before/After Cell Recovery
clean_summary = pd.DataFrame(all_cleaning_log, columns=['Sheet', 'Column', 'Cells_Recovered']) \
    if all_cleaning_log else pd.DataFrame(columns=['Sheet', 'Column', 'Cells_Recovered'])

fig15, ax = plt.subplots(figsize=(8, 3.2))
ax.axis('off')
audit_text = (
    f"DATA INTEGRATION AUDIT\n"
    f"{'='*46}\n"
    f"Source rows read (8 sheets x 12 replicate rows): 96\n"
    f"Rows retained after replicate-correct merge:     {len(master_df)}\n"
    f"Total numeric cells in master dataset:           {len(master_df)*len(numeric_cols)}\n"
    f"Missing cells remaining:                         {int(master_df[numeric_cols].isna().sum().sum())}\n"
    f"Cells recovered via formatting cleanup:          {len(clean_summary)}\n"
)
if len(clean_summary) > 0:
    for _, r in clean_summary.iterrows():
        audit_text += f"   - {r['Sheet'].strip()} / {r['Column']}: {r['Cells_Recovered']} cell(s)\n"
ax.text(0.02, 0.95, audit_text, family='monospace', fontsize=9.5, va='top')
plt.savefig('outputs/phase_03_eda/viz_15_data_cleaning_audit.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_15_data_cleaning_audit.png')

# VIZ-16: Replicate Consistency Panel - Coefficient of Variation Across All Parameters
cv_summary = stats_df.pivot(index='Parameter', columns='Formulation', values='CV_pct')
fig16, ax = plt.subplots(figsize=(8, 12))
sns.heatmap(cv_summary, cmap='RdYlGn_r', center=10, annot=True, fmt='.1f', cbar_kws={'label': 'CV (%)'}, ax=ax)
ax.set_title('VIZ-16: Replicate Consistency - Coefficient of Variation (%) by Parameter & Formulation\n'
             '(Lower = more reproducible across the 3 replicate batches)', fontsize=10, fontweight='bold')
plt.tight_layout()
plt.savefig('outputs/phase_03_eda/viz_16_replicate_cv_heatmap.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_16_replicate_cv_heatmap.png')

print(f'\n✓ Phase 3 complete: 16 exploratory visuals saved to outputs/phase_03_eda/')

"""## 📈 PHASE 4: Biostatistical Hypothesis Testing  
*8 visuals: VIZ-17 → VIZ-24*
"""

print('\n' + '='*100)
print('PHASE 4: STATISTICAL ANALYSIS')
print('='*100)

test_columns = ['Energy_kcal', 'Protein_pct', 'Fiber_g', 'Hardness_g', 'Overall_Accept',
                 'TPC_mgGAE', 'pH', 'DPPH_pct']

print('\nNORMALITY TESTING (Shapiro-Wilk, pooled across all 12 observations per parameter):')
normality_results = {}
for col in test_columns:
    data = master_df[col].dropna()
    shapiro_stat, shapiro_p = stats.shapiro(data)
    normality_results[col] = {'shapiro_stat': shapiro_stat, 'shapiro_p': shapiro_p}
    consensus = 'Normal' if shapiro_p > 0.05 else 'Non-Normal'
    print(f'{col:<20} Shapiro W={shapiro_stat:.4f}  p={shapiro_p:.4f}  | {consensus}')

print('\nNote: with N=3 per group (12 pooled), the Shapiro-Wilk test has limited power; its')
print('result is reported as a diagnostic alongside the non-parametric Kruskal-Wallis test')
print('below, not as a gatekeeper that determines whether ANOVA is permitted to run.')

# Homogeneity of Variance Testing
print('\nHOMOGENEITY OF VARIANCE TESTING (Levene, center=median):')
homogeneity_results = {}
for col in test_columns:
    groups = [master_df[master_df['Formulation'] == form][col].dropna().values for form in FORMS]
    levene_stat, levene_p = stats.levene(*groups, center='median')
    homogeneity_results[col] = {'levene_stat': levene_stat, 'levene_p': levene_p}
    homo = 'Homogeneous' if levene_p > 0.05 else 'Heterogeneous'
    print(f'{col:<20} Levene={levene_stat:.4f}  p={levene_p:.4f}  | {homo}')

# One-Way ANOVA + Kruskal-Wallis + Effect Size (eta-squared) - now genuinely computable
print('\nANOVA & KRUSKAL-WALLIS ANALYSIS (df_between=3, df_within=8):')
anova_results = {}
for col in test_columns:
    groups = [master_df[master_df['Formulation'] == form][col].dropna().values for form in FORMS]
    f_stat, f_pval = stats.f_oneway(*groups)
    h_stat, h_pval = stats.kruskal(*groups)

    grand_mean = master_df[col].mean()
    ss_between = sum(len(g) * (np.mean(g) - grand_mean) ** 2 for g in groups)
    ss_total = sum((master_df[col] - grand_mean) ** 2)
    eta_sq = ss_between / ss_total if ss_total > 0 else np.nan

    anova_results[col] = {'anova_f': f_stat, 'anova_p': f_pval, 'kw_h': h_stat, 'kw_p': h_pval, 'eta_sq': eta_sq}
    sig = '***' if f_pval < 0.001 else '**' if f_pval < 0.01 else '*' if f_pval < 0.05 else 'ns'
    print(f'{col:<20} F={f_stat:8.3f}  p={f_pval:.4f} {sig:<4} eta2={eta_sq:.3f}  KW-H={h_stat:.3f}  KW-p={h_pval:.4f}')

# Tukey HSD Post-Hoc Pairwise Comparisons (only meaningful now that ANOVA is genuinely powered)
print('\nTUKEY HSD POST-HOC PAIRWISE COMPARISONS:')
tukey_results = {}
for col in test_columns:
    sub = master_df[['Formulation', col]].dropna()
    tukey = pairwise_tukeyhsd(endog=sub[col], groups=sub['Formulation'], alpha=0.05)
    tukey_results[col] = tukey
    print(f'\n{col}:')
    print(tukey.summary())

# Save Statistical Summary (FDR-corrected p-values included, per Section 11 methodological note)
stat_summary = []
raw_pvals = [anova_results[c]['anova_p'] for c in test_columns]
reject, pvals_fdr, _, _ = multipletests(raw_pvals, alpha=0.05, method='fdr_bh')

for col, p_fdr, rej in zip(test_columns, pvals_fdr, reject):
    ar = anova_results[col]
    stat_summary.append({
        'Parameter': col,
        'ANOVA_F': round(ar['anova_f'], 3),
        'ANOVA_p': round(ar['anova_p'], 5),
        'ANOVA_p_FDR': round(p_fdr, 5),
        'Significant_FDR_corrected': 'Yes' if rej else 'No',
        'Eta_Squared': round(ar['eta_sq'], 4),
        'KW_H': round(ar['kw_h'], 3),
        'KW_p': round(ar['kw_p'], 5),
        'Shapiro_p': round(normality_results[col]['shapiro_p'], 4),
        'Levene_p': round(homogeneity_results[col]['levene_p'], 4),
    })

stat_summary_df = pd.DataFrame(stat_summary)
stat_summary_df.to_csv('outputs/phase_04_statistics/01_statistical_summary.csv', index=False)
print('\n✓ Statistical summary (with Benjamini-Hochberg FDR correction across 8 tests) saved')
print(stat_summary_df.to_string(index=False))

# VIZ-17: Normality Diagnostic Panel (histogram per parameter)
fig17, axes = plt.subplots(2, 4, figsize=(16, 7))
for ax, col in zip(axes.flat, test_columns):
    data = master_df[col].dropna()
    ax.hist(data, bins=6, color='#45B7D1', alpha=0.7, edgecolor='white')
    ax.set_title(f'{col}\nShapiro p={normality_results[col]["shapiro_p"]:.3f}', fontsize=9, fontweight='bold')
fig17.suptitle('VIZ-17: Normality Diagnostics - Distribution of Pooled Observations (N=12 each)', fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('outputs/phase_04_statistics/viz_17_normality_panel.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_17_normality_panel.png')

# VIZ-18: Q-Q Plot Grid (visual normality check against theoretical normal quantiles)
fig18, axes = plt.subplots(2, 4, figsize=(16, 7))
for ax, col in zip(axes.flat, test_columns):
    data = master_df[col].dropna()
    stats.probplot(data, dist='norm', plot=ax)
    ax.set_title(col, fontsize=9, fontweight='bold')
    ax.get_lines()[0].set_markerfacecolor('#45B7D1')
    ax.get_lines()[0].set_markeredgecolor('#1A5276')
fig18.suptitle('VIZ-18: Q-Q Plots Against Theoretical Normal Distribution', fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('outputs/phase_04_statistics/viz_18_qq_plots.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_18_qq_plots.png')

# VIZ-19: Levene's Test Statistic & Significance by Parameter
fig19, ax = plt.subplots(figsize=(9, 4.5))
levene_ps = [homogeneity_results[c]['levene_p'] for c in test_columns]
bar_colors = ['#2ECC71' if p > 0.05 else '#E74C3C' for p in levene_ps]
ax.bar(test_columns, levene_ps, color=bar_colors, alpha=0.85)
ax.axhline(0.05, color='black', linestyle='--', linewidth=1, label='alpha = 0.05')
ax.set_ylabel("Levene's test p-value")
ax.set_title('VIZ-19: Homogeneity of Variance Across Formulations (green = homogeneous)', fontweight='bold')
ax.tick_params(axis='x', rotation=30)
ax.legend()
plt.tight_layout()
plt.savefig('outputs/phase_04_statistics/viz_19_homogeneity_bars.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_19_homogeneity_bars.png')

# VIZ-20: ANOVA Significance Forest Plot (F-statistic with significance shading)
fig20 = go.Figure()
f_vals = [anova_results[c]['anova_f'] for c in test_columns]
p_vals = [anova_results[c]['anova_p'] for c in test_columns]
bar_colors = ['#C0392B' if p < 0.05 else '#95A5A6' for p in p_vals]
fig20.add_trace(go.Bar(x=f_vals, y=test_columns, orientation='h', marker_color=bar_colors,
                         text=[f'p={p:.4f}' for p in p_vals], textposition='outside'))
fig20.add_vline(x=stats.f.ppf(0.95, 3, 8), line_dash='dash', line_color='black',
                  annotation_text='F-critical (alpha=0.05, df=3,8)')
fig20.update_layout(title='VIZ-20: ONE-WAY ANOVA F-STATISTICS BY PARAMETER (red = significant at p<0.05)',
                     xaxis_title='F-statistic', height=500, title_x=0.5)
fig20.write_html('outputs/phase_04_statistics/viz_20_anova_forest.html')
log_viz('viz_20_anova_forest.html')

# VIZ-21: Effect Size (eta-squared) Ranking
fig21, ax = plt.subplots(figsize=(9, 4.5))
eta_vals = [anova_results[c]['eta_sq'] for c in test_columns]
order = np.argsort(eta_vals)[::-1]
ax.barh([test_columns[i] for i in order], [eta_vals[i] for i in order], color='#8E44AD', alpha=0.85)
ax.axvline(0.01, color='gray', linestyle=':', label='small (0.01)')
ax.axvline(0.06, color='gray', linestyle='--', label='medium (0.06)')
ax.axvline(0.14, color='gray', linestyle='-', label='large (0.14)')
ax.set_xlabel('Eta-squared (% variance explained by formulation)')
ax.set_title('VIZ-21: Effect Size Ranking Across Tested Parameters', fontweight='bold')
ax.legend(fontsize=8)
plt.tight_layout()
plt.savefig('outputs/phase_04_statistics/viz_21_effect_size_ranking.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_21_effect_size_ranking.png')

# VIZ-22: Tukey HSD Pairwise Significance Grid (Overall_Accept as the flagship sensory outcome)
focus_param = 'Overall_Accept'
tukey_focus = tukey_results[focus_param]
pair_matrix = pd.DataFrame(np.ones((4, 4)), index=FORMS, columns=FORMS, dtype=float)
for row in tukey_focus.summary().data[1:]:
    g1, g2, meandiff, p_adj = row[0], row[1], row[2], row[3]
    pair_matrix.loc[g1, g2] = float(p_adj)
    pair_matrix.loc[g2, g1] = float(p_adj)
pair_arr = pair_matrix.to_numpy(copy=True)
np.fill_diagonal(pair_arr, np.nan)
pair_matrix = pd.DataFrame(pair_arr, index=FORMS, columns=FORMS)

fig22, ax = plt.subplots(figsize=(5.5, 4.8))
sns.heatmap(pair_matrix, annot=True, fmt='.3f', cmap='RdYlGn', vmin=0, vmax=0.1,
            cbar_kws={'label': 'Tukey-adjusted p-value'}, ax=ax)
ax.set_title(f'VIZ-22: Tukey HSD Pairwise p-values - {focus_param}', fontweight='bold', fontsize=10)
plt.tight_layout()
plt.savefig('outputs/phase_04_statistics/viz_22_tukey_pairwise_heatmap.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_22_tukey_pairwise_heatmap.png')

# VIZ-23: Boxplot with Significance Annotation (Overall_Accept, the flagship outcome)
fig23, ax = plt.subplots(figsize=(7, 5.5))
box_data = [master_df[master_df['Formulation'] == f]['Overall_Accept'].values for f in FORMS]
bp = ax.boxplot(box_data, labels=[formulation_map[f] for f in FORMS], patch_artist=True, widths=0.5)
for patch, f in zip(bp['boxes'], FORMS):
    patch.set_facecolor(formulation_colors[f])
    patch.set_alpha(0.7)
for f_idx, f in enumerate(FORMS):
    vals = master_df[master_df['Formulation'] == f]['Overall_Accept'].values
    ax.scatter([f_idx + 1] * len(vals), vals, color='black', zorder=5, s=20)

ar = anova_results['Overall_Accept']
ax.set_title(f"VIZ-23: Overall Acceptance by Formulation\nANOVA F={ar['anova_f']:.2f}, p={ar['anova_p']:.4f}, "
             f"eta2={ar['eta_sq']:.3f}", fontweight='bold', fontsize=10)
ax.set_ylabel('Overall Acceptance (9-pt hedonic scale)')
plt.tight_layout()
plt.savefig('outputs/phase_04_statistics/viz_23_overall_accept_significance.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_23_overall_accept_significance.png')

# VIZ-24: Multi-Parameter Significance Dashboard (raw vs FDR-corrected p-values)
fig24 = go.Figure()
fig24.add_trace(go.Bar(name='Raw ANOVA p', x=test_columns, y=[anova_results[c]['anova_p'] for c in test_columns],
                         marker_color='#3498DB'))
fig24.add_trace(go.Bar(name='FDR-corrected p', x=test_columns, y=list(pvals_fdr), marker_color='#E67E22'))
fig24.add_hline(y=0.05, line_dash='dash', line_color='red', annotation_text='alpha=0.05')
fig24.update_layout(title='VIZ-24: RAW vs. FDR-CORRECTED P-VALUES ACROSS 8 PARAMETERS', barmode='group',
                     yaxis_title='p-value', height=550, title_x=0.5)
fig24.write_html('outputs/phase_04_statistics/viz_24_pvalue_dashboard.html')
log_viz('viz_24_pvalue_dashboard.html')

print(f'\n✓ Phase 4 complete: 8 statistical visuals saved to outputs/phase_04_statistics/')

"""## 🧬 PHASE 5: Multivariate Analysis — PCA, Clustering, Correlation  
*9 visuals: VIZ-25 → VIZ-33*
"""

print('\n' + '='*100)
print('PHASE 5: MULTIVARIATE ANALYSIS')
print('='*100)

analysis_cols = [col for col in master_df.columns if col not in ('Formulation', 'Replicate', 'Formulation_Name')]
X = master_df[analysis_cols].dropna()
X_scaled = StandardScaler().fit_transform(X)
formulations_arr = master_df.loc[X.index, 'Formulation'].values
replicates_arr = master_df.loc[X.index, 'Replicate'].values

pca_full = PCA()
pca_full.fit(X_scaled)
cumulative_variance = np.cumsum(pca_full.explained_variance_ratio_)
n_components = np.argmax(cumulative_variance >= 0.95) + 1
n_components = max(2, min(n_components, X_scaled.shape[1] - 1, X_scaled.shape[0] - 1))

pca = PCA(n_components=n_components)
X_pca = pca.fit_transform(X_scaled)

print(f'\nPCA Results (fit on {X_scaled.shape[0]} replicate-level observations, {X_scaled.shape[1]} features):')
print(f'  Components retained (>=95% variance): {pca.n_components}')
print(f'  Variance explained per component: {[round(v*100,2) for v in pca.explained_variance_ratio_]}')
print(f'  Cumulative variance: {pca.explained_variance_ratio_.sum()*100:.2f}%')
print('\nNote: with N=12 replicate-level observations (vs. N=4 formulation means in the prior')
print('extraction), this PCA is fit on a meaningfully larger and more representative sample,')
print('though still small by general multivariate-statistics standards.')

# VIZ-25: PCA Scree Plot (variance explained per component)
fig25 = make_subplots(specs=[[{'secondary_y': True}]])
comp_labels = [f'PC{i+1}' for i in range(len(pca_full.explained_variance_ratio_))]
fig25.add_trace(go.Bar(x=comp_labels, y=pca_full.explained_variance_ratio_ * 100, name='Individual variance %',
                          marker_color='#4ECDC4'))
fig25.add_trace(go.Scatter(x=comp_labels, y=np.cumsum(pca_full.explained_variance_ratio_) * 100,
                              name='Cumulative variance %', mode='lines+markers', marker_color='#FF6B6B'),
                  secondary_y=True)
fig25.add_hline(y=95, line_dash='dash', line_color='gray', secondary_y=True, annotation_text='95% threshold')
fig25.update_layout(title='VIZ-25: PCA SCREE PLOT - VARIANCE EXPLAINED PER COMPONENT', height=550, title_x=0.5)
fig25.write_html('outputs/phase_05_multivariate/viz_25_scree_plot.html')
log_viz('viz_25_scree_plot.html')

# VIZ-26: PCA Scores Plot (replicate-level, 12 points instead of 4 formulation means)
fig26 = go.Figure()
for form in FORMS:
    mask = formulations_arr == form
    fig26.add_trace(go.Scatter(x=X_pca[mask, 0], y=X_pca[mask, 1], mode='markers+text',
                                  text=[f'R{r}' for r in replicates_arr[mask]], textposition='top center',
                                  name=formulation_map[form],
                                  marker=dict(size=14, color=formulation_colors[form], opacity=0.85,
                                              line=dict(width=1, color='white'))))
fig26.update_layout(title='VIZ-26: PCA SCORES PLOT (Replicate-Level, N=12)',
                      xaxis_title=f'PC1 ({pca.explained_variance_ratio_[0]*100:.1f}%)',
                      yaxis_title=f'PC2 ({pca.explained_variance_ratio_[1]*100:.1f}%)', height=700, title_x=0.5)
fig26.write_html('outputs/phase_05_multivariate/viz_26_pca_2d_replicates.html')
log_viz('viz_26_pca_2d_replicates.html')

# VIZ-27: PCA with Approx. 95% Spread Ellipses per Formulation (replicate clustering tightness)
from matplotlib.patches import Ellipse

fig27, ax = plt.subplots(figsize=(8, 7))
for form in FORMS:
    mask = formulations_arr == form
    pts = X_pca[mask, :2]
    ax.scatter(pts[:, 0], pts[:, 1], color=formulation_colors[form], s=90, label=formulation_map[form],
               edgecolor='white', zorder=5)
    if len(pts) >= 3:
        cov = np.cov(pts.T)
        eigval, eigvec = np.linalg.eigh(cov)
        angle = np.degrees(np.arctan2(eigvec[1, -1], eigvec[0, -1]))
        width, height = 2 * np.sqrt(max(eigval[-1], 1e-9)) * 2.45, 2 * np.sqrt(max(eigval[0], 1e-9)) * 2.45
        ell = Ellipse(xy=pts.mean(axis=0), width=width, height=height, angle=angle,
                       facecolor=formulation_colors[form], alpha=0.15, edgecolor=formulation_colors[form])
        ax.add_patch(ell)
ax.set_xlabel(f'PC1 ({pca.explained_variance_ratio_[0]*100:.1f}%)')
ax.set_ylabel(f'PC2 ({pca.explained_variance_ratio_[1]*100:.1f}%)')
ax.set_title('VIZ-27: PCA with Approx. 95% Replicate-Spread Ellipses per Formulation', fontweight='bold', fontsize=11)
ax.legend()
plt.tight_layout()
plt.savefig('outputs/phase_05_multivariate/viz_27_pca_confidence_ellipses.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_27_pca_confidence_ellipses.png')

# VIZ-28: PCA Loadings - Top Contributing Variables to PC1 and PC2
loadings = pd.DataFrame(pca.components_[:2].T, index=analysis_cols, columns=['PC1', 'PC2'])
top_pc1 = loadings['PC1'].abs().sort_values(ascending=False).head(12).index
top_pc2 = loadings['PC2'].abs().sort_values(ascending=False).head(12).index

fig28, axes = plt.subplots(1, 2, figsize=(13, 5.5))
loadings.loc[top_pc1, 'PC1'].sort_values().plot(kind='barh', ax=axes[0], color='#4ECDC4')
axes[0].set_title('Top 12 Loadings on PC1', fontweight='bold')
loadings.loc[top_pc2, 'PC2'].sort_values().plot(kind='barh', ax=axes[1], color='#FF6B6B')
axes[1].set_title('Top 12 Loadings on PC2', fontweight='bold')
fig28.suptitle('VIZ-28: PCA Component Loadings - Which Variables Drive Each Axis', fontweight='bold', y=1.03)
plt.tight_layout()
plt.savefig('outputs/phase_05_multivariate/viz_28_pca_loadings.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_28_pca_loadings.png')

# VIZ-29: PCA Biplot (scores + top loading vectors overlaid)
fig29, ax = plt.subplots(figsize=(8.5, 7.5))
for form in FORMS:
    mask = formulations_arr == form
    ax.scatter(X_pca[mask, 0], X_pca[mask, 1], color=formulation_colors[form], s=80,
               label=formulation_map[form], edgecolor='white', zorder=5)
top_vars = loadings.abs().sum(axis=1).sort_values(ascending=False).head(8).index
scale = np.abs(X_pca[:, :2]).max() * 0.9
for var in top_vars:
    x_load, y_load = loadings.loc[var, 'PC1'] * scale, loadings.loc[var, 'PC2'] * scale
    ax.annotate('', xy=(x_load, y_load), xytext=(0, 0), arrowprops=dict(arrowstyle='->', color='gray', lw=1.2))
    ax.text(x_load * 1.1, y_load * 1.1, var, fontsize=7.5, ha='center', color='#333333')
ax.axhline(0, color='lightgray', lw=0.8); ax.axvline(0, color='lightgray', lw=0.8)
ax.set_xlabel(f'PC1 ({pca.explained_variance_ratio_[0]*100:.1f}%)')
ax.set_ylabel(f'PC2 ({pca.explained_variance_ratio_[1]*100:.1f}%)')
ax.set_title('VIZ-29: PCA Biplot - Replicate Scores with Top-8 Loading Vectors', fontweight='bold', fontsize=11)
ax.legend(fontsize=8)
plt.tight_layout()
plt.savefig('outputs/phase_05_multivariate/viz_29_pca_biplot.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_29_pca_biplot.png')

# VIZ-30: Full Correlation Matrix (replicate-level, N=12 -- far less small-sample-fragile than N=4)
corr_matrix = master_df[analysis_cols].corr(method='pearson')
fig30 = go.Figure(data=go.Heatmap(z=corr_matrix.values, x=corr_matrix.columns, y=corr_matrix.index,
                                     colorscale='RdBu', zmid=0, zmin=-1, zmax=1))
fig30.update_layout(title='VIZ-30: CORRELATION MATRIX (Replicate-Level, N=12 Observations)', height=1000, width=1200, title_x=0.5)
fig30.write_html('outputs/phase_05_multivariate/viz_30_correlation_full.html')
corr_matrix.to_csv('outputs/phase_05_multivariate/01_correlation_matrix.csv')
log_viz('viz_30_correlation_full.html')

# VIZ-31: High-Correlation Network Graph (|r| > 0.9, excluding self-pairs)
import itertools
edges = []
for c1, c2 in itertools.combinations(analysis_cols, 2):
    r = corr_matrix.loc[c1, c2]
    if pd.notna(r) and abs(r) > 0.9:
        edges.append((c1, c2, r))

fig31, ax = plt.subplots(figsize=(11, 9))
nodes = sorted(set([e[0] for e in edges] + [e[1] for e in edges]))
angle_step = 2 * np.pi / max(len(nodes), 1)
node_pos = {n: (np.cos(i * angle_step), np.sin(i * angle_step)) for i, n in enumerate(nodes)}
for n, (x, y) in node_pos.items():
    ax.scatter(x, y, s=140, color='#45B7D1', zorder=5, edgecolor='white')
    ax.text(x * 1.13, y * 1.13, n, fontsize=7, ha='center', va='center')
for c1, c2, r in edges:
    x1, y1 = node_pos[c1]; x2, y2 = node_pos[c2]
    ax.plot([x1, x2], [y1, y2], color='#E74C3C' if r > 0 else '#3498DB', alpha=0.4, linewidth=abs(r) * 2)
ax.set_xlim(-1.4, 1.4); ax.set_ylim(-1.4, 1.4); ax.axis('off')
ax.set_title(f'VIZ-31: High-Correlation Network (|r| > 0.9, N=12) - {len(edges)} edges among {len(nodes)} variables',
             fontweight='bold', fontsize=11)
plt.tight_layout()
plt.savefig('outputs/phase_05_multivariate/viz_31_correlation_network.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_31_correlation_network.png')

# VIZ-32: Hierarchical Clustering Dendrogram (replicate-level, Ward linkage)
fig32, ax = plt.subplots(figsize=(11, 5.5))
Z = linkage(X_scaled, method='ward')
labels_dendro = [f'{f}{r}' for f, r in zip(formulations_arr, replicates_arr)]
dendro_colors = {f'{f}{r}': formulation_colors[f] for f, r in zip(formulations_arr, replicates_arr)}
dn = dendrogram(Z, labels=labels_dendro, ax=ax, color_threshold=0)
for lbl in ax.get_xticklabels():
    lbl.set_color(dendro_colors.get(lbl.get_text(), 'black'))
ax.set_title('VIZ-32: Hierarchical Clustering Dendrogram (Ward Linkage, Replicate-Level)', fontweight='bold')
ax.set_ylabel('Ward distance')
plt.tight_layout()
plt.savefig('outputs/phase_05_multivariate/viz_32_dendrogram.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_32_dendrogram.png')

cluster_labels = fcluster(Z, t=4, criterion='maxclust')
agreement = pd.crosstab(formulations_arr, cluster_labels)
print('\nHierarchical clustering (k=4) vs. true formulation label cross-tab:')
print(agreement)

# VIZ-33: K-Means Clustering on PCA Space (validates whether unsupervised clusters recover formulations)
km = KMeans(n_clusters=4, random_state=42, n_init=10)
km_labels = km.fit_predict(X_pca[:, :2])

fig33, axes = plt.subplots(1, 2, figsize=(13, 5.5))
for form in FORMS:
    mask = formulations_arr == form
    axes[0].scatter(X_pca[mask, 0], X_pca[mask, 1], color=formulation_colors[form], s=90,
                     label=formulation_map[form], edgecolor='white')
axes[0].set_title('True Formulation Labels', fontweight='bold')
axes[0].set_xlabel('PC1'); axes[0].set_ylabel('PC2'); axes[0].legend(fontsize=8)

scatter = axes[1].scatter(X_pca[:, 0], X_pca[:, 1], c=km_labels, cmap='tab10', s=90, edgecolor='white')
axes[1].set_title('K-Means Cluster Assignment (k=4, unsupervised)', fontweight='bold')
axes[1].set_xlabel('PC1'); axes[1].set_ylabel('PC2')
fig33.suptitle('VIZ-33: Unsupervised K-Means vs. True Formulation Labels', fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('outputs/phase_05_multivariate/viz_33_kmeans_validation.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_33_kmeans_validation.png')

ct = pd.crosstab(formulations_arr, km_labels)
print('\nK-Means (k=4) cluster vs. true formulation cross-tab:')
print(ct)
print(f'\n✓ Phase 5 complete: 9 multivariate visuals saved to outputs/phase_05_multivariate/')

"""## 🛠️ PHASE 6: Composite Feature Engineering"""

print('\n' + '='*100)
print('PHASE 6: COMPOSITE FEATURE ENGINEERING')
print('='*100)

eng_df = master_df.copy()

# Domain-informed engineered ratios, used later as ML features and quality-index inputs
eng_df['FibreCarb_Ratio'] = eng_df['Fiber_g'] / (eng_df['Carb_pct'] + 1e-6)
eng_df['Protein_Energy_Density'] = eng_df['Protein_pct'] / (eng_df['Energy_kcal'] + 1e-6) * 100
eng_df['Mineral_Density_Score'] = eng_df[['Ca_mg', 'Fe_mg', 'Mg_mg', 'Zn_mg']].sum(axis=1) / eng_df['Energy_kcal'] * 100
eng_df['Texture_Cohesion_Ratio'] = eng_df['Firmness_g'] / (eng_df['Hardness_g'] + 1e-6)
eng_df['Antioxidant_Composite'] = (eng_df['TPC_mgGAE'] + eng_df['TFC_mgQE'] / 3 + eng_df['DPPH_pct']) / 3
eng_df['Sensory_Consistency'] = eng_df[['Appearance', 'Colour', 'Texture', 'Flavour', 'Aroma']].std(axis=1)
eng_df['Color_Vividness'] = eng_df['Chroma'] / (eng_df['L_star'] + 1e-6)

engineered_cols = ['FibreCarb_Ratio', 'Protein_Energy_Density', 'Mineral_Density_Score',
                    'Texture_Cohesion_Ratio', 'Antioxidant_Composite', 'Sensory_Consistency', 'Color_Vividness']

eng_df.to_csv('outputs/phase_06_features/01_engineered_features.csv', index=False)
print(f'✓ {len(engineered_cols)} engineered features added to a working copy of the master dataset:')
for c in engineered_cols:
    print(f'   • {c}')
print('\nSummary by formulation:')
print(eng_df.groupby('Formulation')[engineered_cols].mean().round(3))
print('\n✓ Saved -> outputs/phase_06_features/01_engineered_features.csv')

"""## ⚖️ PHASE 7: Cross-Domain Trade-Off Mapping  
*2 visuals: VIZ-34 → VIZ-35*
"""

print('\n' + '='*100)
print('PHASE 7: CROSS-DOMAIN TRADE-OFF MAPPING')
print('='*100)

domain_groups = {
    'Sensory': ['Appearance', 'Colour', 'Texture', 'Flavour', 'Aroma', 'Overall_Accept'],
    'Texture': ['Hardness_g', 'Firmness_g', 'Strength_g'],
    'Antioxidant': ['TPC_mgGAE', 'TFC_mgQE', 'DPPH_pct'],
    'Mineral': ['Na_mg', 'K_mg', 'Ca_mg', 'Zn_mg', 'Fe_mg', 'P_mg', 'I_mg', 'Mg_mg', 'Cu_mg'],
}

domain_scores = {}
for domain, cols in domain_groups.items():
    domain_mean = master_df.groupby('Formulation')[cols].mean()
    domain_norm = (domain_mean - domain_mean.min()) / (domain_mean.max() - domain_mean.min() + 1e-9)
    domain_scores[domain] = domain_norm.mean(axis=1) * 100

tradeoff_df = pd.DataFrame(domain_scores)
tradeoff_df.index = [formulation_map[f] for f in tradeoff_df.index]
tradeoff_df.to_csv('outputs/phase_07_tradeoff/01_domain_tradeoff_scores.csv')

print('\nDomain-level composite scores (0-100, normalized within this 4-formulation batch):')
print(tradeoff_df.round(1))
print('\n✓ Saved -> outputs/phase_07_tradeoff/01_domain_tradeoff_scores.csv')

# VIZ-34: Cross-Domain Trade-Off Radar (Sensory vs Texture vs Antioxidant vs Mineral)
fig34 = go.Figure()
domains = list(domain_groups.keys())
for form in FORMS:
    name = formulation_map[form]
    vals = tradeoff_df.loc[name, domains].values
    fig34.add_trace(go.Scatterpolar(r=vals, theta=domains, fill='toself', name=name,
                                       marker=dict(color=formulation_colors[form]),
                                       fillcolor=formulation_colors[form], opacity=0.35))
fig34.update_layout(title='VIZ-34: CROSS-DOMAIN TRADE-OFF RADAR (Sensory vs Texture vs Antioxidant vs Mineral)',
                      polar=dict(radialaxis=dict(visible=True, range=[0, 100])), height=700, title_x=0.5)
fig34.write_html('outputs/phase_07_tradeoff/viz_34_domain_tradeoff_radar.html')
log_viz('viz_34_domain_tradeoff_radar.html')

# VIZ-35: Sensory-vs-Functional Trade-Off Scatter (the headline trade-off of this study)
tradeoff_df['Functional'] = tradeoff_df[['Antioxidant', 'Mineral']].mean(axis=1)
fig35 = go.Figure()
for form in FORMS:
    name = formulation_map[form]
    fig35.add_trace(go.Scatter(x=[tradeoff_df.loc[name, 'Sensory']], y=[tradeoff_df.loc[name, 'Functional']],
                                  mode='markers+text', text=[name], textposition='top center',
                                  marker=dict(size=22, color=formulation_colors[form]), name=name))
fig35.add_hline(y=tradeoff_df['Functional'].mean(), line_dash='dot', line_color='gray')
fig35.add_vline(x=tradeoff_df['Sensory'].mean(), line_dash='dot', line_color='gray')
fig35.update_layout(title='VIZ-35: SENSORY ACCEPTABILITY vs. FUNCTIONAL (ANTIOXIDANT+MINERAL) PERFORMANCE',
                      xaxis_title='Sensory composite score (0-100)', yaxis_title='Functional composite score (0-100)',
                      height=650, title_x=0.5)
fig35.write_html('outputs/phase_07_tradeoff/viz_35_sensory_vs_functional.html')
log_viz('viz_35_sensory_vs_functional.html')
print(f'\n✓ Phase 6-7 complete: 2 trade-off visuals saved to outputs/phase_07_tradeoff/')

"""## 🤖 PHASE 8: Machine Learning — 9-Algorithm Benchmark + SHAP  
*9 visuals: VIZ-36 → VIZ-44*
"""

print('\n' + '='*100)
print('PHASE 8: MACHINE LEARNING')
print('='*100)

ml_target = 'Overall_Accept'
ml_features = [col for col in analysis_cols if col != ml_target]

X_ml = master_df[ml_features].dropna()
y_ml = master_df.loc[X_ml.index, ml_target]

X_ml_scaled = StandardScaler().fit_transform(X_ml)

X_train, X_test, y_train, y_test, form_train, form_test = train_test_split(
    X_ml_scaled, y_ml, master_df.loc[X_ml.index, 'Formulation'],
    test_size=0.25, random_state=42
)

print(f'\nML Data Prepared:')
print(f'  Training: {X_train.shape[0]} samples  ({list(form_train.values)})')
print(f'  Testing:  {X_test.shape[0]} samples  ({list(form_test.values)})')
print(f'  Features: {X_train.shape[1]}')
print('\nNote: N=12 is still a small dataset for machine learning. This benchmark is reported as')
print('a genuine train/test evaluation (unlike the prior N=4 run, which had no valid test set at')
print('all) but should still be read as a methodological proof-of-concept pending a larger study --')
print('5-fold cross-validation below is the more defensible headline metric than the single split.')

models = {
    'Linear Regression': LinearRegression(),
    'Ridge (a=1.0)': Ridge(alpha=1.0),
    'Lasso (a=0.01)': Lasso(alpha=0.01, max_iter=5000),
    'ElasticNet': ElasticNet(alpha=0.01, max_iter=5000),
    'KNN (k=2)': KNeighborsRegressor(n_neighbors=2),
    'Random Forest': RandomForestRegressor(n_estimators=200, random_state=42, max_depth=5, min_samples_leaf=2),
    'Gradient Boosting': GradientBoostingRegressor(n_estimators=100, random_state=42, max_depth=2, learning_rate=0.05),
    'XGBoost': xgb.XGBRegressor(n_estimators=100, random_state=42, max_depth=2, learning_rate=0.05, verbosity=0),
    'LightGBM': lgb.LGBMRegressor(n_estimators=100, random_state=42, max_depth=2, learning_rate=0.05,
                                    min_child_samples=2, verbose=-1),
}

model_performance = {}
trained_models = {}
cv_scores_all = {}

print(f'\n{"Model":<22} {"Train R2":<11} {"Test R2":<11} {"RMSE":<10} {"MAE":<10} {"5-fold CV R2 (mean+/-sd)":<24}')
print('-' * 90)

kf = KFold(n_splits=5, shuffle=True, random_state=42)
for name, model in models.items():
    model.fit(X_train, y_train)
    trained_models[name] = model

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    train_r2 = r2_score(y_train, y_train_pred)
    test_r2 = r2_score(y_test, y_test_pred)
    rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))
    mae = mean_absolute_error(y_test, y_test_pred)

    cv_scores = cross_val_score(model, X_ml_scaled, y_ml, cv=kf, scoring='r2')
    cv_scores_all[name] = cv_scores

    model_performance[name] = {'train_r2': train_r2, 'test_r2': test_r2, 'rmse': rmse, 'mae': mae,
                                'cv_r2_mean': cv_scores.mean(), 'cv_r2_std': cv_scores.std()}
    print(f'{name:<22} {train_r2:<11.4f} {test_r2:<11.4f} {rmse:<10.4f} {mae:<10.4f} '
          f'{cv_scores.mean():.4f} +/- {cv_scores.std():.4f}')

best_model_name = max(model_performance, key=lambda x: model_performance[x]['cv_r2_mean'])
print(f'\n✓ Best Model by 5-fold CV R2 (the recommended headline metric): {best_model_name}')

# Model Performance Export
perf_df = pd.DataFrame(model_performance).T.sort_values('cv_r2_mean', ascending=False)
perf_df.to_csv('outputs/phase_08_ml/01_model_performance.csv')
print('\n✓ Model performance table (train R2, test R2, RMSE, MAE, 5-fold CV R2 +/- SD) saved')
print(perf_df.round(4).to_string())

# VIZ-36: Model Comparison Dashboard (Test R2, RMSE, MAE, CV R2)
fig36 = make_subplots(rows=2, cols=2, subplot_titles=['Test R2', 'Test RMSE', 'Test MAE', '5-fold CV R2 (mean)'])
fig36.add_trace(go.Bar(y=perf_df.index, x=perf_df['test_r2'], orientation='h', marker_color='#FF6B6B', showlegend=False), row=1, col=1)
fig36.add_trace(go.Bar(y=perf_df.index, x=perf_df['rmse'], orientation='h', marker_color='#4ECDC4', showlegend=False), row=1, col=2)
fig36.add_trace(go.Bar(y=perf_df.index, x=perf_df['mae'], orientation='h', marker_color='#45B7D1', showlegend=False), row=2, col=1)
fig36.add_trace(go.Bar(y=perf_df.index, x=perf_df['cv_r2_mean'], orientation='h', marker_color='#FFA07A',
                          error_x=dict(type='data', array=perf_df['cv_r2_std']), showlegend=False), row=2, col=2)
fig36.update_layout(title_text='VIZ-36: ML MODEL COMPARISON DASHBOARD', height=900, title_x=0.5)
fig36.write_html('outputs/phase_08_ml/viz_36_model_comparison.html')
log_viz('viz_36_model_comparison.html')

# VIZ-37: Predicted vs. Actual Scatter (best model, both train and test points)
best_model = trained_models[best_model_name]
y_train_pred_best = best_model.predict(X_train)
y_test_pred_best = best_model.predict(X_test)

fig37, ax = plt.subplots(figsize=(6.5, 6.5))
ax.scatter(y_train, y_train_pred_best, color='#4ECDC4', s=80, label='Train', edgecolor='white')
ax.scatter(y_test, y_test_pred_best, color='#FF6B6B', s=110, label='Test', edgecolor='white', marker='D')
lims = [min(y_ml.min(), y_train_pred_best.min(), y_test_pred_best.min()) - 0.1,
        max(y_ml.max(), y_train_pred_best.max(), y_test_pred_best.max()) + 0.1]
ax.plot(lims, lims, 'k--', linewidth=1, label='Perfect prediction')
ax.set_xlabel('Actual Overall_Accept'); ax.set_ylabel('Predicted Overall_Accept')
ax.set_title(f'VIZ-37: Predicted vs. Actual - {best_model_name}\n'
             f'(Test R2={model_performance[best_model_name]["test_r2"]:.3f})', fontweight='bold', fontsize=10)
ax.legend()
plt.tight_layout()
plt.savefig('outputs/phase_08_ml/viz_37_predicted_vs_actual.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_37_predicted_vs_actual.png')

# VIZ-38: Residual Diagnostic Plot (best model, test set)
residuals = y_test.values - y_test_pred_best
fig38, axes = plt.subplots(1, 2, figsize=(12, 4.5))
axes[0].scatter(y_test_pred_best, residuals, color='#8E44AD', s=80, edgecolor='white')
axes[0].axhline(0, color='black', linestyle='--')
axes[0].set_xlabel('Predicted value'); axes[0].set_ylabel('Residual (actual - predicted)')
axes[0].set_title('Residuals vs. Predicted', fontweight='bold')
stats.probplot(residuals, dist='norm', plot=axes[1])
axes[1].set_title('Residual Q-Q Plot', fontweight='bold')
fig38.suptitle(f'VIZ-38: Residual Diagnostics - {best_model_name} (Test Set)', fontweight='bold', y=1.02)
plt.tight_layout()
plt.savefig('outputs/phase_08_ml/viz_38_residual_diagnostics.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_38_residual_diagnostics.png')

# VIZ-39: Random Forest Feature Importance (Top 15)
rf_model = trained_models['Random Forest']
importances = pd.Series(rf_model.feature_importances_, index=ml_features).sort_values(ascending=False).head(15)

fig39, ax = plt.subplots(figsize=(8, 6))
importances.sort_values().plot(kind='barh', ax=ax, color='#2ECC71')
ax.set_title('VIZ-39: Random Forest Feature Importance - Top 15 Predictors of Overall_Accept', fontweight='bold', fontsize=10)
ax.set_xlabel('Gini importance')
plt.tight_layout()
plt.savefig('outputs/phase_08_ml/viz_39_rf_feature_importance.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_39_rf_feature_importance.png')

# VIZ-40: SHAP Summary Plot (Random Forest, full feature set)
explainer = shap.TreeExplainer(rf_model)
shap_values = explainer.shap_values(X_ml_scaled)

fig40 = plt.figure(figsize=(9, 7))
shap.summary_plot(shap_values, X_ml_scaled, feature_names=ml_features, show=False, max_display=15)
plt.title('VIZ-40: SHAP Summary Plot - Random Forest, Overall_Accept', fontweight='bold', fontsize=10)
plt.tight_layout()
plt.savefig('outputs/phase_08_ml/viz_40_shap_summary.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_40_shap_summary.png')

# VIZ-41: SHAP Waterfall for a Single Replicate (local explanation)
focus_idx = 0

# TreeExplainer's expected_value/shap_values shape varies by SHAP version and whether the
# model output is single- or multi-output; normalize both to plain 1-D/scalar before plotting.
base_value = explainer.expected_value
if isinstance(base_value, (list, np.ndarray)):
    base_value = np.asarray(base_value).reshape(-1)[0]
base_value = float(base_value)

sv = shap_values
if isinstance(sv, list):
    sv = sv[0]
sv = np.asarray(sv)
if sv.ndim == 3:
    sv = sv[:, :, 0]
row_values = sv[focus_idx].reshape(-1)

fig41 = plt.figure(figsize=(8, 5.5))
expl = shap.Explanation(values=row_values, base_values=base_value,
                          data=X_ml_scaled[focus_idx], feature_names=ml_features)
shap.plots.waterfall(expl, max_display=12, show=False)
plt.title(f'VIZ-41: SHAP Local Explanation - Replicate Index {focus_idx} '
          f'({master_df.loc[X_ml.index[focus_idx], "Formulation_Name"]}, Rep '
          f'{master_df.loc[X_ml.index[focus_idx], "Replicate"]})', fontweight='bold', fontsize=9)
plt.tight_layout()
plt.savefig('outputs/phase_08_ml/viz_41_shap_waterfall.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_41_shap_waterfall.png')

# VIZ-42: Learning Curve (Random Forest, train size vs CV score)
train_sizes, train_scores, val_scores = learning_curve(
    RandomForestRegressor(n_estimators=200, random_state=42, max_depth=5, min_samples_leaf=2),
    X_ml_scaled, y_ml, cv=4, train_sizes=np.linspace(0.4, 1.0, 5), scoring='r2'
)

fig42, ax = plt.subplots(figsize=(7.5, 5))
ax.plot(train_sizes, train_scores.mean(axis=1), 'o-', color='#4ECDC4', label='Training score')
ax.fill_between(train_sizes, train_scores.mean(axis=1)-train_scores.std(axis=1),
                 train_scores.mean(axis=1)+train_scores.std(axis=1), color='#4ECDC4', alpha=0.2)
ax.plot(train_sizes, val_scores.mean(axis=1), 'o-', color='#FF6B6B', label='Validation score')
ax.fill_between(train_sizes, val_scores.mean(axis=1)-val_scores.std(axis=1),
                 val_scores.mean(axis=1)+val_scores.std(axis=1), color='#FF6B6B', alpha=0.2)
ax.set_xlabel('Training set size'); ax.set_ylabel('R2 score')
ax.set_title('VIZ-42: Learning Curve - Random Forest (4-fold CV)', fontweight='bold')
ax.legend()
plt.tight_layout()
plt.savefig('outputs/phase_08_ml/viz_42_learning_curve.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_42_learning_curve.png')

# VIZ-43: Cross-Validation Score Distribution Across All 9 Models
fig43, ax = plt.subplots(figsize=(10, 5))
cv_data = [cv_scores_all[name] for name in perf_df.index]
bp = ax.boxplot(cv_data, labels=perf_df.index, patch_artist=True, vert=True)
for patch in bp['boxes']:
    patch.set_facecolor('#45B7D1'); patch.set_alpha(0.6)
ax.axhline(0, color='gray', linestyle='--', linewidth=0.8)
ax.set_ylabel('5-fold CV R2'); ax.set_title('VIZ-43: Cross-Validation R2 Distribution by Model', fontweight='bold')
ax.tick_params(axis='x', rotation=30)
plt.tight_layout()
plt.savefig('outputs/phase_08_ml/viz_43_cv_score_distribution.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_43_cv_score_distribution.png')

# VIZ-44: Train-Test Gap Diagnostic (overfitting indicator per model)
fig44, ax = plt.subplots(figsize=(9, 5))
gap = perf_df['train_r2'] - perf_df['test_r2']
bar_colors = ['#E74C3C' if g > 0.3 else '#2ECC71' for g in gap]
ax.barh(perf_df.index, gap, color=bar_colors, alpha=0.85)
ax.axvline(0, color='black', linewidth=0.8)
ax.set_xlabel('Train R2 - Test R2  (larger = more overfitting)')
ax.set_title('VIZ-44: Train-Test Performance Gap by Model (Overfitting Diagnostic)', fontweight='bold')
plt.tight_layout()
plt.savefig('outputs/phase_08_ml/viz_44_train_test_gap.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_44_train_test_gap.png')

print(f'\n✓ Phase 8 complete: 9 machine-learning visuals saved to outputs/phase_08_ml/')

"""## 🔬 PHASE 9: Predictive Diagnostics Deep-Dive  
*2 visuals: VIZ-45 → VIZ-46*
"""

print('\n' + '='*100)
print('PHASE 9: PREDICTIVE DIAGNOSTICS DEEP-DIVE')
print('='*100)

print('\nThis phase interprets the Phase 8 machine-learning benchmark rather than re-running it.')
print('Two diagnostics are reported:')
print('  (1) Feature-to-sample ratio context -- 43 candidate features against 9-12 observations')
print('      means every model in Phase 8 is operating far outside the regime in which')
print('      held-out validation is normally considered reliable (a common rule of thumb asks')
print('      for at least 10x as many rows as features; this dataset is roughly 4x short).')
print('  (2) A reduced-feature re-fit, using only the top-5 Random Forest features from VIZ-39,')
print('      to test whether shrinking the feature set materially changes the cross-validated')
print('      picture -- informative for the Future Work recommendation in Section 15.')

top5_features = importances.head(5).index.tolist()
X_ml_reduced = StandardScaler().fit_transform(master_df[top5_features])
kf5 = KFold(n_splits=5, shuffle=True, random_state=42)
rf_reduced = RandomForestRegressor(n_estimators=200, random_state=42, max_depth=5, min_samples_leaf=2)
cv_reduced = cross_val_score(rf_reduced, X_ml_reduced, y_ml, cv=kf5, scoring='r2')

print(f'\nTop-5 features used for the reduced re-fit: {top5_features}')
print(f'Reduced-feature Random Forest 5-fold CV R2: {cv_reduced.mean():.4f} +/- {cv_reduced.std():.4f}')
print(f'(Full 43-feature Random Forest 5-fold CV R2 was: {model_performance["Random Forest"]["cv_r2_mean"]:.4f} '
      f'+/- {model_performance["Random Forest"]["cv_r2_std"]:.4f})')

diag_summary = pd.DataFrame([
    {'Configuration': 'Full feature set (43 features)', 'N_features': 43,
     'CV_R2_mean': model_performance['Random Forest']['cv_r2_mean'],
     'CV_R2_std': model_performance['Random Forest']['cv_r2_std']},
    {'Configuration': 'Top-5 RF-importance features', 'N_features': 5,
     'CV_R2_mean': cv_reduced.mean(), 'CV_R2_std': cv_reduced.std()},
])
diag_summary.to_csv('outputs/phase_09_diagnostics/01_feature_reduction_diagnostic.csv', index=False)
print('\n✓ Saved -> outputs/phase_09_diagnostics/01_feature_reduction_diagnostic.csv')

# VIZ-45: Feature-to-Sample Ratio Context Chart
fig45, ax = plt.subplots(figsize=(8, 4.5))
ratios = {'This study\n(43 features, 12 rows)': 43/12,
          'Rule-of-thumb minimum\n(<=0.1 recommended)': 0.1,
          'Top-5 reduced re-fit\n(5 features, 12 rows)': 5/12}
bar_colors = ['#E74C3C', '#2ECC71', '#F39C12']
ax.bar(list(ratios.keys()), list(ratios.values()), color=bar_colors, alpha=0.85)
ax.axhline(0.1, color='black', linestyle='--', linewidth=1)
ax.set_ylabel('Features-per-observation ratio')
ax.set_title('VIZ-45: Feature-to-Sample Ratio vs. Recommended Practice', fontweight='bold', fontsize=10)
plt.tight_layout()
plt.savefig('outputs/phase_09_diagnostics/viz_45_feature_sample_ratio.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_45_feature_sample_ratio.png')

# VIZ-46: Reduced vs. Full Feature Set -- CV R2 Comparison
fig46, ax = plt.subplots(figsize=(7, 4.5))
configs = diag_summary['Configuration']
means = diag_summary['CV_R2_mean']
stds = diag_summary['CV_R2_std']
ax.bar(configs, means, yerr=stds, capsize=6, color=['#E74C3C', '#2ECC71'], alpha=0.85)
ax.axhline(0, color='black', linewidth=0.8)
ax.set_ylabel('5-fold CV R2')
ax.set_title('VIZ-46: Full vs. Reduced Feature Set - Cross-Validated R2', fontweight='bold', fontsize=10)
ax.tick_params(axis='x', rotation=10)
plt.tight_layout()
plt.savefig('outputs/phase_09_diagnostics/viz_46_reduced_vs_full_cv.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_46_reduced_vs_full_cv.png')

print(f'\n✓ Phase 9 complete: 2 diagnostic visuals saved to outputs/phase_09_diagnostics/')

"""## 🏆 PHASE 10: Composite Quality Indices  
*3 visuals: VIZ-47 → VIZ-49*
"""

print('\n' + '='*100)
print('PHASE 10: QUALITY INDICES')
print('='*100)

def norm_01(col):
    return (col - col.min()) / (col.max() - col.min() + 1e-8)

master_df_idx = master_df.copy()

nqi_cols = ['Protein_pct', 'Fiber_g', 'Ash_g']
master_df_idx['NQI'] = sum(norm_01(master_df_idx[c]) for c in nqi_cols) / len(nqi_cols) * 100

aoi_cols = ['TPC_mgGAE', 'TFC_mgQE', 'DPPH_pct']
master_df_idx['AOI'] = sum(norm_01(master_df_idx[c]) for c in aoi_cols) / len(aoi_cols) * 100

mineral_idx_cols = ['Ca_mg', 'Fe_mg', 'Mg_mg', 'Zn_mg']
master_df_idx['MDI'] = sum(norm_01(master_df_idx[c]) for c in mineral_idx_cols) / len(mineral_idx_cols) * 100

tqi_cols = ['Hardness_g', 'Firmness_g']
master_df_idx['TQI'] = sum(norm_01(master_df_idx[c]) for c in tqi_cols) / len(tqi_cols) * 100

sai_cols = ['Appearance', 'Colour', 'Texture', 'Flavour', 'Aroma', 'Overall_Accept']
master_df_idx['SAI'] = master_df_idx[sai_cols].mean(axis=1) / 10 * 100

master_df_idx['OPEI'] = (master_df_idx['NQI'] * 0.25 + master_df_idx['AOI'] * 0.25 +
                          master_df_idx['MDI'] * 0.15 + master_df_idx['TQI'] * 0.15 +
                          master_df_idx['SAI'] * 0.20)

idx_cols = ['NQI', 'AOI', 'MDI', 'TQI', 'SAI', 'OPEI']
idx_summary = master_df_idx.groupby('Formulation')[idx_cols].mean()
idx_sd = master_df_idx.groupby('Formulation')[idx_cols].std()
idx_summary.index = [formulation_map[f] for f in idx_summary.index]
idx_sd.index = [formulation_map[f] for f in idx_sd.index]

print('\nQUALITY INDEX RANKINGS (mean across 3 replicates per formulation):')
print(idx_summary.round(2))
print('\nQUALITY INDEX VARIABILITY (SD across 3 replicates per formulation):')
print(idx_sd.round(2))

idx_summary.to_csv('outputs/phase_10_indices/01_quality_indices.csv')
idx_sd.to_csv('outputs/phase_10_indices/02_quality_indices_sd.csv')

opei_rank = idx_summary['OPEI'].sort_values(ascending=False)
print('\nOPEI RANKING:')
for rank, (form, score) in enumerate(opei_rank.items(), 1):
    print(f'  {rank}. {form:<20} {score:.2f}')

print('\n✓ Saved -> outputs/phase_10_indices/01_quality_indices.csv')
print('✓ Saved -> outputs/phase_10_indices/02_quality_indices_sd.csv')

# VIZ-47: Composite Quality Indices Heatmap
fig47 = go.Figure(data=go.Heatmap(z=idx_summary.values, x=idx_summary.columns, y=idx_summary.index,
                                     colorscale='YlGnBu', text=np.round(idx_summary.values, 1),
                                     texttemplate='%{text}', textfont={'size': 12}))
fig47.update_layout(title='VIZ-47: QUALITY INDICES HEATMAP (Mean Across 3 Replicates)', height=500, title_x=0.5)
fig47.write_html('outputs/phase_10_indices/viz_47_indices_heatmap.html')
log_viz('viz_47_indices_heatmap.html')

# VIZ-48: OPEI Ranking Bar with Replicate-Level SD Error Bars
code_lookup = {v: k for k, v in formulation_map.items()}
fig48, ax = plt.subplots(figsize=(8, 5))
order = opei_rank.index
means = idx_summary.loc[order, 'OPEI']
sds = idx_sd.loc[order, 'OPEI']
bar_colors_opei = [formulation_colors[code_lookup[name]] for name in order]
ax.bar(order, means, yerr=sds, capsize=6, color=bar_colors_opei, alpha=0.85)
for i, (name, val) in enumerate(means.items()):
    ax.text(i, val + sds[name] + 1.5, f'#{i+1}', ha='center', fontweight='bold')
ax.set_ylabel('Overall Product Excellence Index (OPEI)')
ax.set_title('VIZ-48: OPEI Ranking with Replicate Variability (Mean +/- SD)', fontweight='bold', fontsize=10)
ax.tick_params(axis='x', rotation=15)
plt.tight_layout()
plt.savefig('outputs/phase_10_indices/viz_48_opei_ranking.png', dpi=150, bbox_inches='tight')
plt.close()
log_viz('viz_48_opei_ranking.png')

# VIZ-49: All-Indices Radar + Ranking Podium (combined summary visual)
fig49 = make_subplots(rows=1, cols=2, specs=[[{'type': 'polar'}, {'type': 'bar'}]],
                        subplot_titles=['All Six Indices by Formulation', 'OPEI Podium'])
for form in FORMS:
    name = formulation_map[form]
    fig49.add_trace(go.Scatterpolar(r=idx_summary.loc[name, idx_cols].values, theta=idx_cols, fill='toself',
                                       name=name, marker=dict(color=formulation_colors[form]),
                                       fillcolor=formulation_colors[form], opacity=0.3), row=1, col=1)

podium_order = opei_rank.index.tolist()
podium_colors = [formulation_colors[code_lookup[n]] for n in podium_order]
fig49.add_trace(go.Bar(x=podium_order, y=opei_rank.values, marker_color=podium_colors, showlegend=False), row=1, col=2)

fig49.update_layout(title_text='VIZ-49: COMPOSITE QUALITY SUMMARY - RADAR + OPEI PODIUM', height=600, title_x=0.5)
fig49.write_html('outputs/phase_10_indices/viz_49_indices_radar_podium.html')
log_viz('viz_49_indices_radar_podium.html')

print(f'\n✓ Phase 10 complete: 3 quality-index visuals saved to outputs/phase_10_indices/')

"""## 📦 FINAL: Summary Report, Enhanced Dataset Export & Automatic ZIP Packaging"""

print('\n' + '='*100)
print('FINAL SUMMARY REPORT')
print('='*100)

summary_lines = []
summary_lines.append('GUMMY FORMULATION INTELLIGENCE PLATFORM - V3 RUN SUMMARY')
summary_lines.append('=' * 70)
summary_lines.append(f'Run timestamp: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}')
summary_lines.append('')
summary_lines.append('DATA INTEGRATION')
summary_lines.append(f'  Source file: {excel_file}')
summary_lines.append(f'  Sheets integrated: {len(raw_data)}')
summary_lines.append(f'  Master dataset shape: {master_df.shape[0]} rows x {master_df.shape[1]} columns')
summary_lines.append(f'  Replicates per formulation: {dict(master_df.groupby("Formulation").size())}')
summary_lines.append(f'  Missing values remaining: {int(master_df.isna().sum().sum())}')
summary_lines.append(f'  Cells recovered via cleaning (not imputed, just unmangled): {len(all_cleaning_log)}')
summary_lines.append('')
summary_lines.append('STATISTICAL FINDINGS (Phase 4)')
n_sig = int((stat_summary_df['Significant_FDR_corrected'] == 'Yes').sum())
summary_lines.append(f'  Parameters tested: {len(stat_summary_df)}')
summary_lines.append(f'  Significant after FDR correction (alpha=0.05): {n_sig} of {len(stat_summary_df)}')
summary_lines.append('')
summary_lines.append('MACHINE LEARNING (Phase 8)')
summary_lines.append(f'  Target variable: {ml_target}')
summary_lines.append(f'  Candidate features: {len(ml_features)}')
summary_lines.append(f'  Best model by 5-fold CV R2: {best_model_name} '
                      f'({model_performance[best_model_name]["cv_r2_mean"]:.4f} +/- '
                      f'{model_performance[best_model_name]["cv_r2_std"]:.4f})')
summary_lines.append('  NOTE: with 43 features and 12 rows, cross-validated R2 is negative for most')
summary_lines.append('  models -- an honest signal of severe overfitting risk given this feature-to-')
summary_lines.append('  sample ratio, not a data or code error. See Phase 9 and the accompanying report.')
summary_lines.append('')
summary_lines.append('COMPOSITE QUALITY RANKING (Phase 10, OPEI)')
for rank, (form, score) in enumerate(opei_rank.items(), 1):
    summary_lines.append(f'  {rank}. {form:<20} {score:.2f}')
summary_lines.append('')
summary_lines.append(f'TOTAL VISUALS GENERATED: {VIZ_COUNTER["n"]}')
summary_lines.append('STATUS: ANALYSIS COMPLETE')

summary_text = '\n'.join(summary_lines)
print(summary_text)

with open('outputs/reports/RUN_SUMMARY.txt', 'w') as f:
    f.write(summary_text)
print('\n✓ Run summary saved -> outputs/reports/RUN_SUMMARY.txt')

# Also persist the fully-engineered + index-augmented dataset as the canonical "final dataset"
final_dataset = master_df_idx.merge(
    eng_df[['Formulation', 'Replicate'] + engineered_cols], on=['Formulation', 'Replicate'], how='left'
)
final_dataset.to_csv('outputs/reports/FINAL_ENHANCED_DATASET.csv', index=False)
print(f'✓ Final enhanced dataset ({final_dataset.shape[0]} rows x {final_dataset.shape[1]} columns) '
      f'saved -> outputs/reports/FINAL_ENHANCED_DATASET.csv')

print('\n' + '='*100)
print('CREATING OUTPUT ARCHIVE')
print('='*100)

zip_filename = 'Gummy_Formulation_V3_Complete_Analysis_Outputs.zip'
if os.path.exists(zip_filename):
    os.remove(zip_filename)
shutil.make_archive(zip_filename.replace('.zip', ''), 'zip', 'outputs')
zip_size = os.path.getsize(zip_filename) / (1024 * 1024)

# Build a manifest of every file actually written, grouped by phase folder
manifest = []
for root, _, files in os.walk('outputs'):
    for fname in sorted(files):
        full_path = os.path.join(root, fname)
        manifest.append({'Phase_Folder': os.path.relpath(root, 'outputs'), 'File': fname,
                          'Size_KB': round(os.path.getsize(full_path) / 1024, 1)})
manifest_df = pd.DataFrame(manifest)

print(f'\n✓ ZIP archive: {zip_filename}')
print(f'✓ Size: {zip_size:.2f} MB')
print(f'✓ Total files packaged: {len(manifest_df)}')
print(f'✓ Total visuals generated this run: {VIZ_COUNTER["n"]}')
print('\nFILES BY PHASE FOLDER:')
print(manifest_df.groupby('Phase_Folder').size().to_string())
print('\n✓ READY FOR DOWNLOAD!')

try:
    from google.colab import files
    files.download(zip_filename)
    print(f'✓ Download initiated: {zip_filename}')
except Exception:
    print(f'✓ Archive ready at: {os.path.abspath(zip_filename)}')

print('\n' + '='*100)
print('🎉 ANALYSIS COMPLETE')
print('='*100)
print(f'Timestamp: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}')
print('Status: ✓ SUCCESS')
print(f'\nTotal visuals generated: {VIZ_COUNTER["n"]} (target: 45+)')
print('\nEXTRACT ZIP & EXPLORE:')
print('  • Open .html files in a browser (interactive Plotly charts)')
print('  • Open .png files for static matplotlib/seaborn figures')
print('  • Open .csv files in Excel or pandas (all underlying data)')
print('  • outputs/reports/FINAL_ENHANCED_DATASET.csv is the canonical cleaned + engineered dataset')
print('  • outputs/reports/RUN_SUMMARY.txt is a plain-text recap of every key finding')